### ISSUE TITLE
Sql Query are not logged and getting an exception

### ISSUE THREAD

**Issue by dil-atiwari** [iMacTia/lograge-sql#47]
I am getting the following exception when trying to setup lograge-sql

```ruby
! Unable to load application: NameError: uninitialized constant Lograge::LogSubscribers
 Traceback (most recent call last):
         21: from /usr/local/bundle/gems/ruby/2.5.0/bin/ruby_executable_hooks:24:in `<main>'
         20: from /usr/local/bundle/gems/ruby/2.5.0/bin/ruby_executable_hooks:24:in `eval'
         19: from /usr/local/bundle/gems/ruby/2.5.0/bin/puma:23:in `<main>'
         18: from /usr/local/bundle/gems/ruby/2.5.0/bin/puma:23:in `load'
         17: from /usr/local/bundle/gems/ruby/2.5.0/gems/puma-5.6.4/bin/puma:10:in `<top (required)>'
         16: from /usr/local/bundle/gems/ruby/2.5.0/gems/puma-5.6.4/lib/puma/cli.rb:81:in `run'
         15: from /usr/local/bundle/gems/ruby/2.5.0/gems/puma-5.6.4/lib/puma/launcher.rb:182:in `run'
         14: from /usr/local/bundle/gems/ruby/2.5.0/gems/puma-5.6.4/lib/puma/single.rb:44:in `run'
         13: from /usr/local/bundle/gems/ruby/2.5.0/gems/puma-5.6.4/lib/puma/runner.rb:150:in `load_and_bind'
         12: from /usr/local/bundle/gems/ruby/2.5.0/gems/puma-5.6.4/lib/puma/configuration.rb:270:in `app'
         11: from /usr/local/bundle/gems/ruby/2.5.0/gems/puma-5.6.4/lib/puma/configuration.rb:348:in `load_rackup'
         10: from /usr/local/bundle/gems/ruby/2.5.0/gems/rack-2.2.6.2/lib/rack/builder.rb:66:in `parse_file'
          9: from /usr/local/bundle/gems/ruby/2.5.0/gems/rack-2.2.6.2/lib/rack/builder.rb:105:in `load_file'
          8: from /usr/local/bundle/gems/ruby/2.5.0/gems/rack-2.2.6.2/lib/rack/builder.rb:116:in `new_from_string'
          7: from /usr/local/bundle/gems/ruby/2.5.0/gems/rack-2.2.6.2/lib/rack/builder.rb:116:in `eval'
          6: from config.ru:3:in `block in <main>'
          5: from config.ru:3:in `require'
          4: from /home/app/be/config/environment.rb:2:in `<top (required)>'
          3: from /home/app/be/config/environment.rb:2:in `require_relative'
          2: from /home/app/be/config/application.rb:9:in `<top (required)>'
          1: from /home/app/be/config/application.rb:9:in `require'
 /usr/local/bundle/gems/ruby/2.5.0/gems/lograge-sql-2.1.0/lib/lograge/sql/extension.rb:32:in `<top (required)>': uninitialized constant Lograge::LogSubscribers (NameError)
 uninitialized constant Lograge::LogSubscribers
 /usr/local/bundle/gems/ruby/2.5.0/gems/lograge-sql-2.1.0
```

My configuration

Gemfile.

```ruby
gem 'lograge'
gem 'lograge-sql'
```

Added the below line in my application.rb

```ruby
require 'rails/all'
require 'lograge/sql/extension'
```

```ruby
module Project
  class Application < Rails::Application
  	config.lograge_sql.keep_default_active_record_log = true

    config.lograge.logger = ActiveSupport::Logger.new "#{Rails.root}/log/lograge_#{Rails.env}.log"

    # Add remote IP, client id, hostname, and user id to logs
    config.lograge.custom_options = lambda do |event|
      {
        ip:        event.payload[:ip],
        client_id: event.payload[:client_id],
        hostname:  event.payload[:hostname],
        user_id:   event.payload[:user_id],
        controller: event.payload[:controller],
        action: event.payload[:action],
        params: event.payload[:params],
        exception: event.payload[:exception], 
        exception_object: event.payload[:exception_object]
      }
    end
  end

end
```	

And created the file lograge.rb file inside the initializers folder

```ruby
Rails.application.configure do

  # Instead of extracting event as Strings, extract as Hash. You can also extract
  # additional fields to add to the formatter
  config.lograge_sql.extract_event = Proc.new do |event|
  	{ name: event.payload[:name], duration: event.duration.to_f.round(2), sql: event.payload[:sql] }
  end
  # Format the array of extracted events
  config.lograge_sql.formatter = Proc.new do |sql_queries|
    sql_queries
  end
end
```

Also, if I comment on the below line 

require 'lograge/sql/extension'

And replace with the below line

require 'lograge/active_record_log_subscriber'

So, the error is not shown but the SQL queries are not logged in the lograge_development.log. Can someone help me with this issue?

Rails - 5.2.8.1
Ruby - 2.5.8

**Comment by iMacTia** [comment]
Closing as stale. Happy to reopen if the issue is still there
